
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: yiman
        url: jdbc:postgresql://localhost:5434/postgres
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
